sql.driver: "mysql"
sql.database.name: "root:password@/todo_app"

app.server.port: "8080"
app.access.log.location: "access.log"
app.log.location: "application.log"
fiber.log.format: "[${time}] ${ip} ${method} ${url} - ${status} ${latency} ${bytesSent}\n"
